const bancoMusicas = {
    4318: "Capital Inicial - Independência",
    3165: "Capital Inicial - Música Urbana",
    6028: "Capital Inicial - Primeiros Erros",
    1535: "Capital Inicial - Tudo Que Vai",
    5399: "Capital Inicial - Veraneio Vascaína",
    4909: "Aerosmith - I Don't Want To Miss A Thing",
    2601: "Beatles - All My Loving",
    4518: "Beatles - Help!",
    4714: "Beatles - Hey Jude",
    4525: "Beatles - I Wanna Hold Your Hand",
    4534: "Beatles - Let It Be",
    4936: "Beatles - Love Me Do",
    4965: "Beatles - She Loves You",
    4793: "Beatles - Twist and Shout",
    4559: "Beatles - Yesterday",
    4858: "Bon Jovi - Always",
    9606: "Bon Jovi - Blaze Of Glory",
    5922: "Bon Jovi - I'll Be There For You",
    4923: "Bon Jovi - It's My Life",
    4933: "Bon Jovi - Livin' On A Prayer",
    9224: "Bon Jovi - Misunderstood",
    5946: "Bon Jovi - Never Say Goodbye ",
    9998: "Bon Jovi - Someday I'll Be Saturday Night",
    4996: "Bon Jovi - You Give Love A Bad Name",
    9619: "Dire Straits - Money For Nothing",
    9556: "Dire Straits - So Far Away",
    9234: "Dire Straits - Sultans Of Swing",
    9889: "Dire Straits - Walk Of Life",
    9239: "Dire Straits - Your Latest Trick",
    4562: "Elvis Presley - Always on My Mind",
    4571: "Elvis Presley - Bridge Over Troubled Water",
    4618: "Elvis Presley - Burning Love",
    4572: "Elvis Presley - Can't Help Falling In Love",
    9125: "Elvis Presley - Hound Dog",
    4524: "Elvis Presley - It's Now or Never",
    1918: "Elvis Presley - Love Me Tender",
    4779: "Elvis Presley - Suspicious Minds",
    9695: "Elvis Presley - Sweet Caroline",
    9918: "Elvis Presley - Sylvia",
    4778: "Elvis Presley - Unchained Melody",
    2639: "Guns N' Roses  - You Could Be Mine",
    9094: "Guns N' Roses - Don't Cry",
    4930: "Guns N' Roses - Knockin' on Heavens Door",
    9148: "Guns N' Roses - November Rain",
    9140: "Guns N' Roses - Patience",
    9146: "Guns N' Roses - Sweet Child o' Mine",
    2075: "Guns N' Roses - Used To Love Her",
    6699: "Iron Maiden - Aces High",
    9463: "Iron Maiden - Fear of the Dark",
    6698: "Iron Maiden - Running Free",
    6697: "Iron Maiden - Wasted Years",
    2659: "Iron Maiden - Wasting Love",
    9044: "Katy Perry - California Gurls",
    9189: "Katy Perry - Roar",
    4569: "Kim Carnes - Bette Davis Eyes",
    2551: "Lady Gaga - Bad Romance",
    9908: "Lady Gaga, Bradley Cooper - Shallow",
    9895: "Maroon 5 - Girls Like You",
    9233: "Maroon 5 - Sugar",
    9070: "Matchbox 20 - Unwell",
    4867: "Meredith Brooks - Bitch",
    2586: "Metallica - Enter Sandman",
    9264: "Metallica - Nothing Else Matters",
    9311: "Metallica - The Unforgiven",
    9017: "Queen - Crazy Little Thing Called Love",
    1923: "Queen - Don't Stop Me Now",
    4937: "Queen - Love Of My Life",
    4967: "Queen - Somebody To Love",
    5919: "Queen - Want To Break Free",
    4797: "Queen - We Are The Champions",
    1945: "Red Hot Chili Peppers - By the Way",
    4952: "Red Hot Chili Peppers - Otherside",
    4962: "Red Hot Chili Peppers - Scar Tissue",
    4986: "Red Hot Chili Peppers - Under The Bridge",
    4874: "Lenny Kravitz - Can't Get You Off My Mind",
    4854: "Lenny Kravitz - Again",
    9218: "Lenny Kravitz - Fly Away",
    2589: "Shakira -  No Creo",
    3662: "Shakira - Estoy Aqui",
    6149: "Shakira - Waka Waka",
    2606: "ACDC - Highway to Hell",
    2370: "ACDC - You Shook Me All Night Long"
};
